
# vim: set noai ts=4 sw=4 expandtab:

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  debug-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Debug
      run: make buildtype=debug

  test-build:
    runs-on: ubuntu-latest
    needs: [debug-build]

    steps:
    - uses: actions/checkout@v3
    
    - name: Build Test
      run: make buildtype=test

  release-build:
    runs-on: ubuntu-latest
    needs: [test-build]
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Release
      run: make



















